# Generated by Django 4.1.3 on 2023-03-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ssl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=511)),
                ('issuedto', models.CharField(max_length=63)),
                ('issuedby', models.CharField(max_length=63)),
                ('validfrom', models.CharField(max_length=63)),
                ('validto', models.CharField(max_length=63)),
                ('validdays', models.CharField(max_length=63)),
                ('certivalid', models.CharField(max_length=63)),
                ('certisn', models.CharField(max_length=63)),
                ('certiver', models.CharField(max_length=63)),
                ('certialgo', models.CharField(max_length=63)),
                ('expired', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=511)),
                ('ip', models.CharField(max_length=63)),
            ],
        ),
    ]
