# Generated by Django 4.1.3 on 2023-05-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='statusCode',
            new_name='status_code',
        ),
    ]
