# Generated by Django 4.1.3 on 2023-03-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ssl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=511)),
                ('issuedto', models.CharField(max_length=63)),
                ('issuedby', models.CharField(max_length=63)),
                ('validfrom', models.CharField(max_length=63)),
                ('validto', models.CharField(max_length=63)),
                ('validdays', models.CharField(max_length=63)),
                ('certivalid', models.CharField(max_length=63)),
                ('certisn', models.CharField(max_length=63)),
                ('certiver', models.CharField(max_length=63)),
                ('certialgo', models.CharField(max_length=63)),
                ('expired', models.CharField(max_length=63)),
            ],
        ),
    ]
