# Generated by Django 4.1.3 on 2023-04-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_brokenurls'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlChecked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=31)),
                ('hits', models.IntegerField()),
                ('broken_links_num', models.IntegerField()),
            ],
        ),
    ]
