# Generated by Django 4.1.3 on 2023-04-09 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_urlchecked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('P', 'pending'), ('A', 'active')], default='P', max_length=1)),
                ('user', models.ManyToManyField(blank=True, related_name='site', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='brokenurls',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.site'),
        ),
        migrations.AddField(
            model_name='securesocketslayerscertificate',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.site'),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.site'),
        ),
    ]
